Fix docstring and formats
starkbank/sdk-go pull request #3
Opened 2023-02-01 17:20 UTC by leandro-stark

2023-02-02 17:11 UTC, xavier-stark requested changes

2023-02-02 17:11 UTC, xavier-stark commented on starkbank/transfer/transfer.go
> +//	- Scheduled [time.Time, default now]: date when the transfer will be processed. May be pushed to next business day if necessary. ex: time.Date(2020, 3, 10, 10, 30, 0, 0, time.UTC) or ex: time.Date
tinha um schedule que era só datetime e esse é só date, ai fiquei um pouco confuso

2023-02-02 17:11 UTC, xavier-stark commented on starkbank/utilitypayment/log/log.go
> +	//	- slice of UtilityPayment structs with updated attributes
tem uns que come com S maiúsculo e outros minúsculo, era bom deixar em um padrão
Acho q um crtl shift F "- Slice" deve funcionar

2023-02-02 17:11 UTC, xavier-stark commented on starkbank/workspace/workspace.go
> +	//      - status [string, default nil]: current Workspace status. Options: "active" or "blocked"
a indentação do status ta diferente dos outros

2023-03-02 19:18 UTC, leandro-stark commented on starkbank/brcodepayment/br_code_payment.go
> +//	- Scheduled [time.Time, default now]: Payment scheduled datetime. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),
aceita

2023-03-02 19:19 UTC, leandro-stark commented on starkbank/transfer/transfer.go
> +//	- Scheduled [time.Time, default now]: date when the transfer will be processed. May be pushed to next business day if necessary. ex: time.Date(2020, 3, 10, 10, 30, 0, 0, time.UTC) or ex: time.Date
Alguns scheduled são diferentes mesmo

2023-03-06 22:02 UTC, xavier-stark requested changes

2023-03-06 22:02 UTC, xavier-stark commented on tests/sdk/transfer_test.go
> +	"github.com/starkbank/sdk-go/starkbank/transfer"
aqui tbm n?

2023-03-06 22:02 UTC, xavier-stark commented on tests/utils/examples/examples.go
> +		Url:           fmt.Sprintf("https://webhook.site/2%v", rand.Intn(20-11)),
2?

2023-03-07 17:33 UTC, leandro-stark commented on starkbank/boletopayment/boleto_payment.go
> +	Created        string   `json:",omitempty"`
Neste caso em específico, sim

2023-03-07 17:34 UTC, leandro-stark commented on tests/sdk/balance_test.go
> +	"github.com/starkbank/sdk-go/starkbank/balance"
Não

2023-03-10 21:53 UTC, xavier-stark approved these changes

2023-03-17 18:36 UTC, merged